# Generated by Django 3.1.5 on 2021-01-18 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=36)),
                ('label', models.CharField(max_length=256)),
                ('structure', models.CharField(choices=[('Unincorporated', 'Unincorporated'), ('Non-Profit', 'Non-Profit'), ('Business', 'Business')], default='Unincorporated', max_length=16)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('url', models.CharField(max_length=512)),
            ],
            options={
                'verbose_name_plural': 'Communities',
            },
        ),
        migrations.CreateModel(
            name='EventCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastSeen', models.BigIntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(choices=[('Balboa', 'Balboa'), ('Blues', 'Blues'), ('Boogie Woogie', 'Boogie Woogie'), ('Charleston', 'Charleston'), ("Chicago Steppin'", "Chicago Steppin'"), ('East Coast Swing', 'East Coast Swing'), ('Fusion', 'Fusion'), ('Lindy Hop', 'Lindy Hop'), ('Shag', 'Shag'), ('West Coast Swing', 'West Coast Swing')], default='Lindy Hop', max_length=32)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communities.community')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailAddress', models.EmailField(default='', max_length=254)),
                ('phoneNumber', models.CharField(default='', max_length=64)),
                ('url', models.CharField(default='', max_length=512)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communities.community')),
            ],
        ),
        migrations.AddIndex(
            model_name='community',
            index=models.Index(fields=['uuid'], name='communities_uuid_424ed8_idx'),
        ),
    ]
