# Generated by Django 3.1.5 on 2021-01-15 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeAdded', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=256)),
                ('data', models.JSONField(default=dict)),
            ],
        ),
    ]
