# Generated by Django 3.1.5 on 2021-01-26 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singular', models.TextField()),
                ('plural', models.TextField(null=True)),
                ('location', models.TextField(null=True)),
                ('context', models.TextField(null=True)),
            ],
        ),
    ]
